//
//  AudioPlayer.swift
//  ShibaInuGameShow
//
//  Created by Cecily Kerns on 2/20/19.
//  Copyright © 2019 Cecily Kerns. All rights reserved.
//

import SpriteKit

public class AudioPlayer {
    
    static let shared = AudioPlayer()
    
    @discardableResult func play(sound: Sound, on scene: SKScene) -> SKAudioNode? {
        if sound.type == .effect {
            // Prevents a stutter in the game
            DispatchQueue.global(qos: .background).async {
                // Run an action on our scene
                // That action is a SKAction
                // It will be generated by our playSoundFileNamed function
                // That function takes a fileName
                // and waitForCompletion (a boolean!)
                
                // sound.fileName is "Woof"
                // sound.fileExtension is "mp3"
                //
                // "Woof" + "." + "mp3" = "Woof.mp3"
                
                scene.run(SKAction.playSoundFileNamed(sound.fileName + "." + sound.fileExtension, waitForCompletion: false))
            }
        } else {
            // Background Music
            guard let fileUrl = Bundle.main.url(forResource: sound.fileName, withExtension: sound.fileExtension) else {
                return nil
            }
            
            let node = SKAudioNode(url: fileUrl)
            node.autoplayLooped = true
            return node
        }
        
        return nil
    }
    
}

struct Sound {
    
    var fileName: String
    var fileExtension: String
    
    var type: SoundType
    
}

enum SoundType {
    
    case effect
    case background
    
}
